/* Autogenerated CCD Topology Discovery Header for the X3D Toggle Project
*
* `ccd.h` - Header only
*
* AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
* EDIT FILE: `ccd.sh`
*/
                
#ifndef CCD_H
#define CCD_H
#define TOTAL_CORES 4
#define CCD1_START 4
#define CCD0_CORE_MASK "0-3"
#define LOGICAL_TO_PHYSICAL(logical_core) ((logical_core) % (TOTAL_CORES / 2))
                
void logical_to_physical(int logical_core, int *physical_core);
void start_core_to_logical(int start_core, int *logical_core);
void total_core_to_logical(int total_core, int *logical_core);
void start_core_to_physical(int start_core, int *physical_core);
void total_core_to_physical(int total_core, int *physical_core);
void l3_cache_to_logical(int l3_cache, int *logical_core);
void l3_cache_to_physical(int l3_cache, int *physical_core);
int ccd(char *mask, int *ccd1_start, int *total_cores);
#endif
