# Advanced Networking Toggles for the X3D Toggle Project
# `networking.conf`
# These are some networking settings that are recommended for a gaming system.
# These settings are not all recommended for all systems.
# USE AT YOUR OWN DISCRETION. Not all settings are available on all systems.

# --- [NETWORKING SETTINGS] ---
# System Request functionality of the kernel (SYNC)
# Use kernel.sysrq = 1 to allow all keys.
# See https://docs.kernel.org/admin-guide/sysrq.html for a list
# of values and keys.
kernel.sysrq = 16

# Append the PID to the core filename
kernel.core_uses_pid = 1

# Bump the numeric PID range to make PID collisions less likely.
# 2^22 and 2^15 is possible maximum of 64bit and 32bit kernels respectively.
kernel.pid_max = 4194304

# Source route verification
# Toggled via sysctl
net.ipv4.conf.default.rp_filter = 2
net.ipv4.conf.*.rp_filter = 2

# Do not accept source routing
# Toggled via sysctl
net.ipv4.conf.default.accept_source_route = 0
net.ipv4.conf.*.accept_source_route = 0

# Promote secondary addresses when the primary address is removed
# Toggled via sysctl
net.ipv4.conf.default.promote_secondaries = 1
net.ipv4.conf.*.promote_secondaries = 1

# Fair Queue CoDel packet scheduler to fight bufferbloat
# Toggled via sysctl
-net.core.default_qdisc = fq_codel

# ping(8) without CAP_NET_ADMIN and CAP_NET_RAW
# The upper limit is set to 2^31-1. Values greater than that get rejected by
# the kernel because of this definition in linux/include/net/ping.h:
#   #define GID_T_MAX (((gid_t)~0U) >> 1)
# That's not so bad because values between 2^31 and 2^32-1 are reserved on
# systemd-based systems anyway: https://systemd.io/UIDS-GIDS#summary
-net.ipv4.ping_group_range = 0 2147483647

# --- [SERVER SETTINGS] ---
[Server]
# Enable the server module - default is false.
ENABLED=false
# Set the server IP address - Default is 127.0.0.1.
SERVER_ADDRESS=127.0.0.1
# Set the server port - Default is 9370.
SERVER_PORT=9370
# ssh/remote/local - Default is local. If ssh/remote, use SERVER_SSH_PORT to specify the port.
# If ssh/remote, use SERVER_SSH_USER to specify the user.
SERVER_SSH=local
SERVER_SSH_USER=user
SERVER_SSH_PORT=9371