##  Path                                            Mode  User  Group      Age  Argument
d   /etc/x3d-toggle.d                               0775  root  x3d-toggle  -    -
f   /etc/x3d-toggle.d/daemon.conf                   0664  root  x3d-toggle  -    -
d   /var/log/x3d-toggle/audits                      0775  root  x3d-toggle  -    -
d   /var/log/x3d-toggle/logs                        0775  root  x3d-toggle  -    -
d   /run/x3d-toggle                                 0775  root  x3d-toggle  -    -
d   /var/lib/x3d-toggle                             0775  root  x3d-toggle  -    -
d   /var/log/x3d-toggle/coredumps                   0775  root  x3d-toggle  -    -
z   /sys/devices/platform/AMDI*/amd_x3d_mode        0660  root  x3d-toggle  -    -
z   /sys/bus/platform/drivers/amd_x3d_vcache/bind   0660  root  x3d-toggle  -    -
z   /sys/bus/platform/drivers/amd_x3d_vcache/unbind 0660  root  x3d-toggle  -    -

## Filesystem MAC/DAC provisioning for the X3D Toggle Project
## `tmpfiles.conf` installs to `/usr/lib/tmpfiles.d/x3d_toggle-tmpfiles.conf`
## end of file
